repos:

  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.2.1
      hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: check-docstring-first
      -   id: check-json
      -   id: check-added-large-files
          args: ['--maxkb=5000']
      -   id: check-yaml
      -   id: double-quote-string-fixer

  -   repo: https://github.com/ambv/black
      rev: 19.3b0
      hooks:
      - id: black
        args: ["--line-length", "100", "--skip-string-normalization"]
